name: Update EPL Table Image
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests pillow
      - name: Run Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cd ${{ github.workspace }}
          python epl_table.py
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add epl_table.png
          git commit -m "update table" || echo "No changes to commit"
          git push
